// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Kanban__CardDragndropController from "./kanban/card_dragndrop_controller"
application.register("kanban--card-dragndrop", Kanban__CardDragndropController)

import Kanban__ColumnMenuController from "./kanban/column_menu_controller"
application.register("kanban--column-menu", Kanban__ColumnMenuController)

import Kanban__FilterGroupController from "./kanban/filter_group_controller"
application.register("kanban--filter-group", Kanban__FilterGroupController)

import ProfileController from "./profile_controller"
application.register("profile", ProfileController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import Ui__AccordionController from "./ui/accordion_controller"
application.register("ui--accordion", Ui__AccordionController)

import Ui__CheckboxController from "./ui/checkbox_controller"
application.register("ui--checkbox", Ui__CheckboxController)

import Ui__DialogController from "./ui/dialog_controller"
application.register("ui--dialog", Ui__DialogController)

import Ui__DropdownController from "./ui/dropdown_controller"
application.register("ui--dropdown", Ui__DropdownController)

import Ui__FilterController from "./ui/filter_controller"
application.register("ui--filter", Ui__FilterController)

import Ui__PopoverController from "./ui/popover_controller"
application.register("ui--popover", Ui__PopoverController)

import Ui__ToastController from "./ui/toast_controller"
application.register("ui--toast", Ui__ToastController)
