require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/card_comments", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CardComment. As you add validations to CardComment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CardComment.create! valid_attributes
      get card_comments_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      card_comment = CardComment.create! valid_attributes
      get card_comment_url(card_comment)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_card_comment_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      card_comment = CardComment.create! valid_attributes
      get edit_card_comment_url(card_comment)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CardComment" do
        expect {
          post card_comments_url, params: { card_comment: valid_attributes }
        }.to change(CardComment, :count).by(1)
      end

      it "redirects to the created card_comment" do
        post card_comments_url, params: { card_comment: valid_attributes }
        expect(response).to redirect_to(card_comment_url(CardComment.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CardComment" do
        expect {
          post card_comments_url, params: { card_comment: invalid_attributes }
        }.to change(CardComment, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post card_comments_url, params: { card_comment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested card_comment" do
        card_comment = CardComment.create! valid_attributes
        patch card_comment_url(card_comment), params: { card_comment: new_attributes }
        card_comment.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the card_comment" do
        card_comment = CardComment.create! valid_attributes
        patch card_comment_url(card_comment), params: { card_comment: new_attributes }
        card_comment.reload
        expect(response).to redirect_to(card_comment_url(card_comment))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        card_comment = CardComment.create! valid_attributes
        patch card_comment_url(card_comment), params: { card_comment: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested card_comment" do
      card_comment = CardComment.create! valid_attributes
      expect {
        delete card_comment_url(card_comment)
      }.to change(CardComment, :count).by(-1)
    end

    it "redirects to the card_comments list" do
      card_comment = CardComment.create! valid_attributes
      delete card_comment_url(card_comment)
      expect(response).to redirect_to(card_comments_url)
    end
  end
end
